[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:bot]
command=python -u /app/bot.py
autorestart=true
stdout_logfile=/var/log/supervisor/bot.log
stderr_logfile=/var/log/supervisor/bot.log
